const colors = {
  light: {
    text: "#0F172A",
    tint: "#1565C0",
    background: "#F8FAFC",
    foreground: "#0F172A",
    card: "#FFFFFF",
    cardForeground: "#0F172A",
    primary: "#1565C0",
    primaryForeground: "#FFFFFF",
    primaryLight: "#E3F2FD",
    secondary: "#1565C0",
    secondaryForeground: "#FFFFFF",
    secondaryLight: "#E3F2FD",
    muted: "#F1F5F9",
    mutedForeground: "#546E7A",
    accent: "#0277BD",
    accentForeground: "#FFFFFF",
    accentLight: "#E1F5FE",
    destructive: "#C62828",
    destructiveForeground: "#FFFFFF",
    destructiveLight: "#FFEBEE",
    border: "#CBD5E1",
    input: "#E2E8F0",
    success: "#2E7D32",
    successForeground: "#FFFFFF",
    successBg: "#E8F5E9",
    warning: "#E65100",
    warningBg: "#FFF3E0",
    errorBg: "#FFEBEE",
    surplusBg: "#E8F5E9",
    shadow: "rgba(13, 71, 161, 0.14)",
    headerGradientStart: "#0D47A1",
    headerGradientEnd: "#1565C0",
  },
  radius: 16,
};

export default colors;
